# Generated by Django 4.1.6 on 2023-02-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='is_onboarded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
